const ActionType = {
  // AUTHENTICATION
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  // USER
  INIT_USER_BY_USERNAME: "INIT_USER_BY_USERNAME",

  SET_USER_ID: "SET_USER_ID",
  RESET_USER_ID: "RESET_USER_ID",
  SET_USERNAME: "SET_USERNAME",
  RESET_USERNAME: "RESET_USERNAME",
  SET_USER_DATETIME: "SET_USER_DATETIME",
  RESET_USER_DATETIME: "RESET_USER_DATETIME",
};

export default ActionType;
