const ActionType = {
  // AUTHENTICATION
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  // USER
  RESET_USER_REDUCER: "RESET_USER_REDUCER",

  INIT_USER_BY_USERNAME: "INIT_USER_BY_USERNAME",
  INIT_USER_BY_USERNAME_SUCCESS: "INIT_USER_BY_USERNAME_SUCCESS",
  INIT_USER_BY_USERNAME_FAILED: "INIT_USER_BY_USERNAME_FAILED",

  SET_USER_ID: "SET_USER_ID",
  RESET_USER_ID: "RESET_USER_ID",

  SET_USERNAME: "SET_USERNAME",
  RESET_USERNAME: "RESET_USERNAME",

  SET_USER_DATETIME: "SET_USER_DATETIME",
  RESET_USER_DATETIME: "RESET_USER_DATETIME",
};

export default ActionType;
