const ActionType = {
  // AUTHENTICATION
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  // USER
  GET_USER_BY_ID: "GET_USER_BY_ID",

  SET_USER_ID: "SET_USER_ID",
  RESET_USER_ID: "RESET_USER_ID",
  SET_USERNAME: "SET_USERNAME",
  RESET_USERNAME: "RESET_USERNAME",
};

export default ActionType;
